### ISSUE TITLE
using git 

### ISSUE THREAD

**Issue by rvsandeep** [architshukla/SHA-2#2]
we both will be working on the same file, how are you thinking of handling the merge conflict that might arise.

**Comment by architshukla** [comment]
It should not cause a merge conflict because we are working on different functions and not altering each others code. If you can divide the part into more files then go ahead.

**Comment by rvsandeep** [comment]
hmm ok.. i'll look into it.. if it's not going to cause merge conflict if we work on different functions it would be alright..
but is it not going to compare based on lines..

**Comment by architshukla** [comment]
I think it's much smarter :smile: Don't worry and start whenever you like

**Comment by rvsandeep** [comment]
hmm ok :)
